#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys
import signal
import logging
from time import sleep

from dynhost_lib import get_config, browse_config


def main():
    config = get_config()

    loop_time_sec = int(config.get(config.default_section, 'loop_time_sec'))

    def handle_sighup(signum, frame):
        logger = logging.getLogger('DynHost')
        logger.warn('reloading configuration')
        get_config(config)

    signal.signal(signal.SIGHUP, handle_sighup)

    if '--loop' in sys.argv:
        while True:
            browse_config(config)
            sleep(loop_time_sec)
    else:
        browse_config(config)


if __name__ == '__main__':
    main()
